language: node_js
before_script:
  - npm run build
script:
  - npm test
node_js:
  - "12"
env:
  global:
    - HOST=localhost
    - PORT=3000
    - GROUPME_BOTID="botid"
    - GROUPME_TOKEN="token"
