version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm i
      - run: npm run build
      - run:
          environment:
            HOST: localhost
            PORT: "3000"
            GROUPME_BOTID: "botid"
            GROUPME_TOKEN: "token"
            FP_MPBKEY: "mpbkey"
          command: npm test
